[[mappings]]
description = "Maps Baseline ComStock building types to AEO 2021 commercial building types"
file = "dimension_mappings/lookup_comstock_to_aeo2021_com_bldg_types.csv"
[mappings.from_dimension]
dimension_id = "comstock_bldgtypes_xxx" # <---
type = "metric"
version = "1.0.0"
[mappings.to_dimension]
dimension_id = "aeo2021_com_bldgtypes_xxx" # <---
type = "metric"
version = "1.0.0"
